substitutions:
  device_name: m5-1g-1
  friendly_name: M5 1G 1

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: arsmarthome.m5-1g
    version: "1.0.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 0s

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

switch:
  - platform: gpio
    id: relay_1
    name: "Switch 1"
    pin: GPIO23
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: led1
    on_turn_off:
      - light.turn_off: led1

output:
  - platform: ledc
    pin: GPIO18
    frequency: 1000 Hz
    id: pwm_output

  - platform: gpio
    id: relay_led
    pin: GPIO19

light:
  - platform: monochromatic
    output: pwm_output
    name: "Backlight LEDs"

  - platform: binary
    id: led1
    name: "Touch LED"
    output: relay_led

  - platform: status_led
    name: "WiFi Status"
    pin:
      number: GPIO5
      inverted: true

binary_sensor:
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay_1
