esphome:
  project:
    name: "AR Smart Home.M5-2GANG WITH LONG PRESS"
    version: "1.0.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:



# ---------------------------
# STATUS LED
# ---------------------------
status_led:
  pin:
    number: GPIO5
    inverted: true

# ---------------------------
# RESTART
# ---------------------------
button:
  - platform: restart
    name: "Restart"

# ---------------------------
# RELAYS
# ---------------------------
switch:
  - platform: gpio
    id: relay_1
    name: "Switch 1"
    pin: GPIO23
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    id: relay_2
    name: "Switch 2"
    pin: GPIO19
    restore_mode: RESTORE_DEFAULT_OFF

  # Virtual relay (for scripts)
  - platform: template
    id: relay_3
    internal: true
    optimistic: true
    turn_on_action: []
    turn_off_action: []

  - platform: template
    id: backlight_switch
    name: "Backlight Switch"
    lambda: |-
      return id(backlight_leds).current_values.is_on();
    turn_on_action:
      - light.turn_on: backlight_leds
    turn_off_action:
      - light.turn_off: backlight_leds

# ---------------------------
# BACKLIGHT
# ---------------------------
output:
  - platform: ledc
    pin: GPIO18
    frequency: 1000 Hz
    id: pwm_output

light:
  - platform: monochromatic
    id: backlight_leds
    output: pwm_output
    name: "Backlight LEDs"

# ---------------------------
# BUTTONS
# ---------------------------
binary_sensor:
  - platform: gpio
    id: button_1
    name: "Button 1"
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

    on_press:
      then:
        - script.execute:
            id: start_button_press
            button: 1

    on_release:
      then:
        - script.execute:
            id: release_button_press
            button: 1

  - platform: gpio
    id: button_2
    name: "Button 2"
    pin:
      number: GPIO15
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

    on_press:
      then:
        - script.execute:
            id: start_button_press
            button: 2

    on_release:
      then:
        - script.execute:
            id: release_button_press
            button: 2
