esphome:
  project:
    name: "AR Smart Home.TX-1G"
    version: "1.0.0"

esp8266:
  board: esp01_1m

logger:

# ---------------------------
# BUTTON
# ---------------------------
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      - light.toggle: light_1

  - platform: status
    name: "Device Status"

# ---------------------------
# OUTPUT (RELAY)
# ---------------------------
output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

# ---------------------------
# LIGHT (RESTORE LAST STATE)
# ---------------------------
light:
  - platform: binary
    name: "Light 1"
    id: light_1
    output: relay_1
    restore_mode: RESTORE_DEFAULT_OFF

# ---------------------------
# STATUS LED
# ---------------------------
status_led:
  pin:
    number: GPIO13
    inverted: true

# ---------------------------
# PREFERENCES
# ---------------------------
preferences:
  flash_write_interval: 1min
