############################################
# 🔧 AR SMART HOME – M5 2G SETUP
# 👉 EDIT BEFORE FLASHING
############################################

substitutions:
  device_name: "PUT_DEVICE_NAME_HERE"
  friendly_name: "PUT_FRIENDLY_NAME_HERE"

############################################
# WIFI
############################################
wifi:
  ssid: "PUT_WIFI_NAME_HERE"
  password: "PUT_WIFI_PASSWORD_HERE"
  fast_connect: true
  reboot_timeout: 0s

############################################
# API / OTA
############################################
api:

ota:
  platform: esphome
  password: "PUT_OTA_PASSWORD_HERE"

############################################
# DEVICE NAME
############################################
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

############################################
# PACKAGE
############################################
packages:
  device:
    url: https://github.com/marsh4200/ar-devices
    ref: main
    file: devices/m5-2g-advanced.yaml
