############################################
# AR SMART HOME - TX 3G LONG PRESS SETUP
# EDIT BEFORE FLASHING
############################################

substitutions:
  device_name: "PUT_DEVICE_NAME_HERE"
  friendly_name: "PUT_FRIENDLY_NAME_HERE"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

wifi:
  ssid: "PUT_WIFI_NAME_HERE"
  password: "PUT_WIFI_PASSWORD_HERE"
  reboot_timeout: 0s

api:
  reboot_timeout: 0s

ota:
  platform: esphome

packages:
  gesture_config:
    url: https://github.com/marsh4200/ar-devices
    ref: main
    file: devices/tx/longpress/config/long_press_3g.yaml
    refresh: 0min

  device:
    url: https://github.com/marsh4200/ar-devices
    ref: main
    file: devices/tx/longpress/tx-3g-longpress.yaml
    refresh: 0min
